stages:
  - codecheck
  - test

# WORKFLOW RULES
# ------------------------------------------------------------------------------------------------------
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_COMMIT_BRANCH'
# ------------------------------------------------------------------------------------------------------


# TEMPLATES
# ------------------------------------------------------------------------------------------------------
.base_template:
  image: python:3.7-bullseye
  tags:
    - build
    - internet
  before_script:
    - pip install -e .[dev] --prefer-binary

.venv_template:
  image: python:3.7-bullseye
  tags:
    - build
    - internet
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - python -m pip install -e .[dev] --prefer-binary
# --------------------------------------------------------------------------------------------------


# JOBS
# ------------------------------------------------------------------------------------------------------

# CODE CHECK BY PRE-COMMIT HOOKS
pre-commit_hooks_MR:
  extends: .base_template
  stage: codecheck
  script:
    - apt-get update && apt-get install -y -q git
    - git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA | xargs pre-commit run --files
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
# ------------------------------------------------------------------------------------------------------

# FORMATTING


# TESTS
test_kconfserver:
  extends: .base_template
  stage: test
  script:
    - cd test/kconfserver/
    - ./test_kconfserver.py

test_gen_kconfig_doc:
  extends: .base_template
  stage: test
  script:
    - cd test/gen_kconfig_doc/
    - ./test_target_visibility.py
    - ./test_kconfig_out.py

test_kconfgen:
  extends: .base_template
  stage: test
  script:
    - cd test/kconfgen/
    - ./test_kconfgen.py

test_kconfcheck:
  extends: .base_template
  stage: test
  script:
    - cd test/kconfcheck/
    - ./test_kconfcheck.py

# TESTS in VENV
test_kconfgen_venv:
  extends: .venv_template
  stage: test
  script:
    - cd test/kconfserver/
    - ./test_kconfserver.py

test_kconfgen_venv:
  extends: .venv_template
  stage: test
  script:
    - cd test/gen_kconfig_doc/
    - ./test_target_visibility.py
    - ./test_kconfig_out.py

test_kconfgen_venv:
  extends: .venv_template
  stage: test
  script:
    - cd test/kconfgen/
    - ./test_kconfgen.py

test_kconfcheck_venv:
  extends: .venv_template
  stage: test
  script:
    - cd test/kconfcheck/
    - ./test_kconfcheck.py
