name: Check pre-commit

on:
  pull_request:

jobs:
  check-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-python@master
        with:
          python-version: '3.8'
      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: pip-compile
